on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: inspect secret
        env:
          SECRET: ${{ secrets.TEST }}
        run: |
          echo Password is $SECRET
          if [[ $SECRET == *"TEST"* ]]; then
            echo "This is the secret set in reusable repo!"
          else
            echo "This is secret is NOT recognized"
          fi
